export const QUESTIONS = [
  'Name 3 things that are normally white.',
  'Name 3 things that are normally black.',
  'Name 3 things that you find at a church.',
  'Name 3 things that you tie.',
  'Name 3 tools.',
  'Name 3 winter clothing items.',
  'Name 3 summer clothing items.',
  'Name 3 things you can see in the sky at day.',
  "Name 3 things that begin with 'B'.",
  'Name 3 things that are funny.',
  'Name 3 best presents.',
  'Name 3 worst presents.',
  'Name 3 free things.',
  'Name 3 things that you pop.',
  'Name 3 things that smell bad.',
  'Name 3 types of jewelry.',
  'Name 3 things you might find in the garage.',
  'Name 3 car manufacturers.',
  'Name 3 brands of computers.',
  'Name 3 types of fish.',
  'Name 3 famous animals.',
  'Name 3 bones of the body.',
  'Name 3 birds.',
  'Name 3 animals that growl.',
  'Name 3 animals that are herbivores.',
  'Name 3 insects.',
  'Name 3 animals that would make bad pets.',
  'Name 3 zoo animals.',
  'Name 3 farm animals.',
  'Name 3 mathematical symbols.',
  'Name 3 universities.',
  'Name 3 degrees.',
  'Name 3 countries in Africa.',
  'Name 3 capital cities.',
  'Name 3 types of weather.',
  'Name 3 states in America.',
  'Name 3 countries starting with M.',
  'Name 3 international airports.',
  'Name 3 countries in South America.',
  'Name 3 boy names begnning with D.',
  'Name 3 girl names beginning with D.',
  'Name 3 boy names beginning with A.',
  'Name 3 girl names beginning with A.',
  'Name 3 famous Johns.',
  'Name 3 famous female athletes.',
  'Name 3 famous criminals.',
  'Name 3 American Presidents.',
  'Name 3 monarchs.',
  'Name 3 actors.',
  'Name 3 actresses.',
  'Name 3 cartoon characters.',
  'Name 3 bands.',
  'Name 3 superheroes.',
  'Name 3 famous bald people.',
  'Name 3 TV shows you have never watched.',
  'Name 3 sitcoms.',
  'Name 3 social media sites.',
  'Name 3 books that were turned into films.',
  'Name 3 breakfast foods.',
  'Name 3 foods you have to peel before eating.',
  'Name 3 foods that are sweet.',
  'Name 3 things made of chocolate.',
  'Name 3 things you put ketchup on.',
  'Name 3 foods that can be used in the bedroom.',
  'Name 3 things you would like to accomplish in your lifetime.',
  'Name 3 superpowers that you would like to have.',
  'Name 3 people who live on your street.',
  'Name 3 things you do before going to bed.',
  'Name 3 things you do after waking up.',
  'Name 3 apps that you use.',
  'Name 3 things you do while no one is looking.',
  'Name 3 people that you would date.',
  'Name 3 things you do before going to bed.',
  'Name 3 things you do after waking up.',
  'Name 3 things you do at the weekend.',
  'Name 3 places that you can go skiing.',
  'Name 3 things you should not do at a wedding.',
  'Name 3 things you would do in front of a fire.',
  "Name 3 things you can't do in the dark.",
  'Name 3 excuses for not doing your homework.',
  'Name 3 things you do at Christmas.',
  'Name 3 phobias.',
  'Name 3 reasons to get fired.',
  'Name 3 romantic getaways.',
  'Name 3 wedding destinations.',
  'Name 3 things bridesmaids do.',
  'Name 3 ways to propose.',
  'Name 3 things groomsmen do.',
  'Name 3 date night activities.',
  'Name 3 things you need to plan a wedding.',
  'Name 3 reasons to get married.',
  'Name 3 things you do when you are angry.',
  'Name 3 words that rhyme with date.',
  "Name 3 words that end in 'ful'.",
  'Name 3 words with more 8 letters.',
  'Name 3 Christmas traditions.',
  'Name 3 Christmas songs.',
  'Name 3 Christmas ornaments.',
  'Name 3 dances.',
  'Name 3 love songs.',
];
