export const QUESTIONS = [
  'Name 3 things that are normally white.',
  'Name 3 things that are normally black.',
  'Name 3 things that are normally yellow.',
  'Name 3 things that are pink.',
  'Name 3 things that you find at a church.',
  'Name 3 things that you tie.',
  'Name 3 tools.',
  'Name 3 winter clothing items.',
  'Name 3 summer clothing items.',
  'Name 3 things you can see in the sky at day.',
  "Name 3 things that begin with 'B'.",
  "Name 3 things that begin with 'G'.",
  'Name 3 things that are funny.',
  'Name 3 best presents.',
  'Name 3 worst presents.',
  'Name 3 free things.',
  'Name 3 things that you pop.',
  'Name 3 things that smell bad.',
  'Name 3 types of jewelry.',
  'Name 3 things you might find in the garage.',
  'Name 3 things that cost less than $1.',
  'Name 3 things that cost more than $100000.',
  'Name 3 things with buttons.',
  'Name 3 things with stripes.',
  'Name 3 things with zips.',
  'Name 3 things in your room that begin with T.',
  'Name 3 things in a toolbox.',
  'Name 3 things you put in the car.',
  'Name 3 things that come in pairs.',
  'Name 3 metals.',
  'Name 3 things that create a lot of noise.',
  'Name 3 things that you can breakfast.',
  'Name 3 parts of a bicycle.',
  'Name 3 things that can you find in a bag.',
  'Name 3 triangular objects.',
  'Name 3 round objects.',
  'Name 3 red foods.',
  'Name 3 things you can find in the bedroom.',
  'Name 3 places you can become a regular at.',
  'Name 3 things that have locks.',
  'Name 3 objects you might find in a garden.',
  'Name 3 car manufacturers.',
  'Name 3 brands of computers.',
  'Name 3 electrical appliances.',
  'Name 3 types of fish.',
  'Name 3 famous animals.',
  'Name 3 bones of the body.',
  'Name 3 birds.',
  'Name 3 animals that growl.',
  'Name 3 animals that are herbivores.',
  'Name 3 insects.',
  'Name 3 animals that would make bad pets.',
  'Name 3 zoo animals.',
  'Name 3 farm animals.',
  'Name 3 flowers.',
  'Name 3 baby animals.',
  'Name 3 mythical creatures.',
  'Name 3 animals that growl.',
  "Name 3 animals that start with 'D'.",
  'Name 3 mathematical symbols.',
  'Name 3 universities.',
  'Name 3 degrees.',
  'Name 3 numbers that add up to 1000.',
  'Name 3 elements from the periodic table.',
  'Name 3 countries in Africa.',
  'Name 3 capital cities.',
  'Name 3 types of weather.',
  'Name 3 states in America.',
  'Name 3 countries starting with M.',
  'Name 3 international airports.',
  'Name 3 countries in South America.',
  'Name 3 landmarks.',
  'Name 3 honeymoon destinations.',
  'Name 3 big rivers in the world.',
  'Name 3 boy names begnning with D.',
  'Name 3 girl names beginning with D.',
  'Name 3 boy names beginning with A.',
  'Name 3 girl names beginning with A.',
  'Name 3 boy names beginning with B.',
  'Name 3 boy names beginning with L.',
  'Name 3 girl names beginning with L.',
  'Name 3 famous Johns.',
  'Name 3 famous female athletes.',
  'Name 3 famous criminals.',
  'Name 3 American Presidents.',
  'Name 3 monarchs.',
  'Name 3 actors.',
  'Name 3 actresses.',
  'Name 3 cartoon characters.',
  'Name 3 bands.',
  'Name 3 superheroes.',
  'Name 3 famous bald people.',
  'Name 3 millionaires.',
  'Name 3 comedians.',
  'Name 3 famous chefs.',
  'Name 3 inventors.',
  'Name 3 famous blondes.',
  'Name 3 celebrities with tattoos.',
  'Name 3 famous people with glasses.',
  'Name 3 famous female singers.',
  'Name 3 famous male singers.',
  'Name 3 assassinated world leaders.',
  'Name 3 of your bad habits.',
  'Name 3 TV shows you have never watched.',
  'Name 3 sitcoms.',
  'Name 3 social media sites.',
  'Name 3 books that were turned into films.',
  'Name 3 TV game shows.',
  'Name 3 reality TV shows.',
  'Name 3 movie villains.',
  'Name 3 animal characters on TV.',
  'Name 3 Mario characters.',
  'Name 3 musicials.',
  'Name 3 Disney films.',
  'Name 3 comedy shows.',
  'Name 3 Matt Damon movies.',
  'Name 3 movies with Dwayne Johnson.',
  'Name 3 TV shows that came out in the last year.',
  'Name 3 movies that were a complete waste of time.',
  'Name 3 breakfast foods.',
  'Name 3 foods you have to peel before eating.',
  'Name 3 foods that are sweet.',
  'Name 3 things made of chocolate.',
  'Name 3 things you put ketchup on.',
  'Name 3 foods that can be used in the bedroom.',
  'Name 3 types of chocolate bars.',
  'Name 3 things you might eat at a barbeque.',
  'Name 3 things you buy at a bakery.',
  'Name 3 Chinese foods.',
  'Name 3 foods that take less than 2 minutes to make.',
  'Name 3 things you would like to accomplish in your lifetime.',
  'Name 3 superpowers that you would like to have.',
  'Name 3 people who live on your street.',
  'Name 3 things you do before going to bed.',
  'Name 3 things you do after waking up.',
  'Name 3 apps that you use.',
  'Name 3 things you do while no one is looking.',
  'Name 3 people that you would date.',
  'Name 3 jobs you never want to have.',
  'Name 3 streets near your home.',
  'Name 3 people that you want to date.',
  'Name 3 pet peeves.',
  'Name 3 songs that annoy you.',
  'Name 3 things that make your laugh.',
  'Name 3 things that make you go "woooohoooo!".',
  'Name 3 things that annoyed your parents.',
  'Name 3 things you do before going to bed.',
  'Name 3 things you do after waking up.',
  'Name 3 things you do at the weekend.',
  'Name 3 places that you can go skiing.',
  'Name 3 things you should not do at a wedding.',
  'Name 3 things you would do in front of a fire.',
  "Name 3 things you can't do in the dark.",
  'Name 3 excuses for not doing your homework.',
  'Name 3 things you do at Christmas.',
  'Name 3 phobias.',
  'Name 3 reasons to get fired.',
  'Name 3 romantic getaways.',
  'Name 3 wedding destinations.',
  'Name 3 things bridesmaids do.',
  'Name 3 ways to propose.',
  'Name 3 things groomsmen do.',
  'Name 3 date night activities.',
  'Name 3 things you need to plan a wedding.',
  'Name 3 reasons to get married.',
  'Name 3 things you do when you are angry.',
  'Name 3 things you can do with your eyes closed.',
  'Name 3 sports where jumping is involved.',
  'Name 3 winter activities.',
  'Name 3 summer activities.',
  'Name 3 terrible jobs.',
  'Name 3 things to do on your birthday.',
  'Name 3 ways you can disguise yourself.',
  'Name 3 ways to make money.',
  'Name 3 sporting trophies.',
  'Name 3 jobs that are dangerous.',
  'Name 3 things many people only do once a week.',
  "Name 3 sports that don't use a ball.",
  'Name 3 sports where something is thrown.',
  "Name 3 things you aren't allowed to do at a job interview.",
  'Name 3 games children play on the playground.',
  'Name 3 words that rhyme with date.',
  "Name 3 words that begin with 'ap'.",
  "Name 3 words that end in 'ful'.",
  'Name 3 words with more 8 letters.',
  'Name 3 french words.',
  'Name 3 idioms or proverbs.',
  'Name 3 Christmas traditions.',
  'Name 3 Christmas songs.',
  'Name 3 Christmas ornaments.',
  'Name 3 dances.',
  'Name 3 love songs.',
  'Name 3 clothes shops.',
];
